### ISSUE TITLE
Issues setting up project

### ISSUE THREAD

**Issue by FelixHenninger** [enjoy-digital/nexys-soc#1]
Hej Florent, hi everyone,

thanks a lot for your work on this awesome project! Being fairly new to the FPGA world, I'm loving `litex`, and I'm sure that I'm moving much faster, and that I've learnt a lot more (and had more fun) through it than I would have learnt using traditional HDLs.

I'd love to get this repo running on my Nexys, and I'm trying to build it in an up-to-date [`litex-buildenv`](https://github.com/timvideos/litex-buildenv/) environment provided by the [`HDMI2USB` project](https://github.com/timvideos/HDMI2USB-litex-firmware). However, I'm running into a few issues.

When trying to build the project, the first message is that `UART_INTERRUPT` is undeclared:
```
felix@felix-VirtualBox:~/litex/nexys-soc-master$ ./nexys_video.py --cpu-type lm32
make: Entering directory '/home/felix/litex/nexys-soc-master/build/software/libcompiler_rt'
make: Nothing to be done for 'all'.
make: Leaving directory '/home/felix/litex/nexys-soc-master/build/software/libcompiler_rt'
make: Entering directory '/home/felix/litex/nexys-soc-master/build/software/libbase'
 CC       exception.o
 CC       system.o
 CC       id.o
 CC       uart.o
/home/felix/litex/HDMI2USB-litex-firmware/third_party/litex/litex/soc/software/libbase/uart.c: In function 'uart_write':
/home/felix/litex/HDMI2USB-litex-firmware/third_party/litex/litex/soc/software/libbase/uart.c:84:31: error: 'UART_INTERRUPT' undeclared (first use in this function)
  irq_setmask(oldmask & ~(1 << UART_INTERRUPT));
                               ^
/home/felix/litex/HDMI2USB-litex-firmware/third_party/litex/litex/soc/software/libbase/uart.c:84:31: note: each undeclared identifier is reported only once for each function it appears in
/home/felix/litex/HDMI2USB-litex-firmware/third_party/litex/litex/soc/software/libbase/uart.c: In function 'uart_init':
/home/felix/litex/HDMI2USB-litex-firmware/third_party/litex/litex/soc/software/libbase/uart.c:104:36: error: 'UART_INTERRUPT' undeclared (first use in this function)
  irq_setmask(irq_getmask() | (1 << UART_INTERRUPT));
                                    ^
/home/felix/litex/HDMI2USB-litex-firmware/third_party/litex/litex/soc/software/libbase/Makefile:22: recipe for target 'uart.o' failed
make: *** [uart.o] Error 1
make: Leaving directory '/home/felix/litex/nexys-soc-master/build/software/libbase'
Traceback (most recent call last):
  File "./nexys_video.py", line 142, in <module>
    main()
  File "./nexys_video.py", line 138, in main
    vns = builder.build()
  File "/home/felix/litex/HDMI2USB-litex-firmware/third_party/litex/litex/soc/integration/builder.py", line 154, in build
    self._generate_software(not self.soc.integrated_rom_initialized)
  File "/home/felix/litex/HDMI2USB-litex-firmware/third_party/litex/litex/soc/integration/builder.py", line 128, in _generate_software
    subprocess.check_call(["make", "-C", dst_dir, "-f", makefile])
  File "/home/felix/litex/HDMI2USB-litex-firmware/build/conda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-C', '/home/felix/litex/nexys-soc-master/build/software/libbase', '-f', '/home/felix/litex/HDMI2USB-litex-firmware/third_party/litex/litex/soc/software/libbase/Makefile']' returned non-zero exit status 2.
```

I think I've traced that one down to a recent commit in litex that [makes it possible to delete this interrupt](https://github.com/enjoy-digital/litex/commit/43f8c230a7971b87e9f0a3a2a4acd434a986db63#diff-5b5aa398d41ddd6086fbe51e97931f5c), and after undoing that there's a new error message due to (surprise) overlapping interrupt IRQs:

```
(LX P=nexys_video) felix@felix-VirtualBox:~/litex/nexys-soc-master$ ./nexys_video.py --cpu-type lm32
Traceback (most recent call last):
  File "./nexys_video.py", line 142, in <module>
    main()
  File "./nexys_video.py", line 133, in main
    soc = VideoSoC(platform, **soc_sdram_argdict(args))
  File "./nexys_video.py", line 31, in __init__
    base_cls.__init__(self, platform, *args, **kwargs)
  File "/home/felix/litex/nexys-soc-master/nexys_base.py", line 163, in __init__
    BaseSoC.__init__(self, *args, **kwargs)
  File "/home/felix/litex/nexys-soc-master/nexys_base.py", line 112, in __init__
    **kwargs)
  File "/home/felix/litex/HDMI2USB-litex-firmware/third_party/litex/litex/soc/integration/soc_sdram.py", line 39, in __init__
    SoCCore.__init__(self, platform, clk_freq, **kwargs)
  File "/home/felix/litex/HDMI2USB-litex-firmware/third_party/litex/litex/soc/integration/soc_core.py", line 177, in __init__
    interrupt, mod_name, interrupt_rmap[interrupt]))
AssertionError: Interrupt vector conflict for IRQ 2, user defined uart conflicts with SoC inbuilt ethmac
```

Not being very familiar with the structure of the SoCs, I'm kinda stuck here. Could you give me some pointers as to how to proceed? Is there a known good version of `litex` that builds this project?

I would massively appreciate any hints, and would be glad to help debug this to the fullest extent I can. Thanks again for making all of this possible, I would 💜 to get this running!

Best,

-Felix

**Comment by enjoy-digital** [comment]
Hi Felix,

thanks for using/testing this. Sorry for the troubles, this repository was not up to date. Things should be fine now, you can update litex/nexys-soc and you should be able to build the design.

**Comment by FelixHenninger** [comment]
Hi Florent,

wow, thanks soo much for your super-fast response -- Just like that, it works! You, kind sir, are a true wizard.

I'm going to take a closer look at this tomorrow, and play around a little. I would love to stabilize 1080p support in `HDMI2USB` (it might be me, but I'm getting loads of errors), if there's anything I can do in that regard, pointers are very welcome if you can spare a moment.

Ok, so much for now -- I owe you a portion of your preferred beverage, that's for sure!

All the very best, and thanks again!

-Felix
